# Generated by Django 5.2.11 on 2026-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Nazwa sklepu')),
                ('store_description', models.TextField(blank=True, verbose_name='Opis sklepu')),
            ],
            options={
                'verbose_name': 'Ustawienia sklepu',
                'verbose_name_plural': 'Ustawienia sklepu',
            },
        ),
    ]
