# Generated by Django 5.2.11 on 2026-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_storesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='navbar_color',
            field=models.CharField(choices=[('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue')], default='orange', max_length=20, verbose_name='Navbar color'),
        ),
    ]
